apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-ui-config
data:
  API_HOST: "flask-api-service"
  UM_HOST: "flask-user-management-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-user-management-config
data:
  DB_HOST: "NOTSET"
  DB_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-api-config
data:
  DB_HOST: "NOTSET"
  DB_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: database
