apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: ubk8751/flask-api:latest 
        imagePullPolicy: Always
        env:
        - name: DATABASE_URI
          value: postgresql://myuser:mypassword@postgresql/mydatabase
        command: ["/bin/sh", "-c", "echo Hello from Flask App; sleep infinity"]
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-api
  type: LoadBalancer
