apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-user-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-user-management
  template:
    metadata:
      labels:
        app: flask-user-management
    spec:
      containers:
        - name: flask-user-management
          image: ubk8751/flask-user-management:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: flask-user-management-config
---
apiVersion: v1
kind: Service
metadata:
  name: flask-user-management-service
spec:
  type: LoadBalancer
  selector:
    app: flask-user-management
  ports:
    - port: 5001
      targetPort: 5001
